version: '3.8'

services:
  # Aplicación Flask
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fade-financiacion-app
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DATABASE_PATH=/app/data/programas_financiacion.json
      - SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub
      - LOG_DIR=/app/logs
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    ports:
      - "8000:8000"
    depends_on:
      - selenium
    networks:
      - fade-network
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 --timeout 120 --access-logfile - --error-logfile - app:app

  # Selenium con Chrome headless
  selenium:
    build:
      context: ./docker/selenium
      dockerfile: Dockerfile
    container_name: fade-selenium
    restart: unless-stopped
    shm_size: 2gb
    environment:
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_SESSION_TIMEOUT=300
    ports:
      - "4444:4444"
    networks:
      - fade-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  fade-network:
    driver: bridge

volumes:
  data:
  logs:
  uploads:
